### ISSUE TITLE
homework completed

### ISSUE THREAD

**Issue by hatelove** [jaceju/91-tdd-day2-homework#1]
唯一不確定的地方，就是第五個測試案例完成後的那一連串重構，是不是不小心把後面的需求邏輯也放進來了。

**Comment by jaceju** [comment]
對，這邊我原本是想重做演算法，但看來是太早把後面的邏輯放進來了。

感謝 91 哥指正！

**Comment by jaceju** [comment]
從那個 commit 重新練習過了，然後把原來錯的部份移到 [wrong-example](https://github.com/jaceju/91-tdd-day2-homework/tree/wrong-example) 這個 branch 上。
